[build-system]
requires      = ["setuptools>=80", "setuptools-scm[simple]>=8"]
build-backend = "setuptools.build_meta"

[project]
name            = "openbimxd"
description     = "Add your description here"
dynamic         = ["version"]
readme          = "README.md"
requires-python = ">=3.12"
license         = { file = "LICENSE" }

authors = [
    { name = "Fabian Kaufmann", email = "fabian.kaufmann@rptu.de" },
    { name = "Marius Schellen", email = "marius.schellen@rptu.de" },
    { name = "Mahdi Chamseddine", email = "mahdi.chamseddine@dfki.de" },
]

dependencies = [
    "ifcopenshell",
    "numpy",
    "pystruct3d @ https://github.com/humantecheu/pystruct3d.git",
    "scipy",
]

[tool.ruff]
exclude      = [".eggs", ".git", ".venv"]
line-length  = 88                         # same as black
indent-width = 4

[tool.ruff.format]
quote-style = "double"
preview     = true
[tool.ty.environment]
extra-paths = ["../pystruct3d/"]

# [tool.pyright]
# extraPaths = ["../pystruct3d/"]

[tool.uv.sources]
pystruct3d = { workspace = true }
